drop_columns = [
    "unique_user_id",
    "user_soi_timestamp",
    "user_soi_date",
    "log_user_revenue_usd_30d",
    "log_user_revenue_usd_60d",
    "log_user_revenue_usd_90d",
    "sub1",
    "sub2",
    "site_id",
    "user_site_id",
    "if_mach3",
    "user_registration_email_domain",
    "user_body_type",
    "user_first_order_device",
    "user_birth_year",
    "user_height",
    "user_is_google_signup",
    "cum_perc_revenue_usd_hourly_09",  # this is essentially 0 or 1 for some reason
    # leave for now
    "email_days_since_first_soi",
    "email_days_since_previous_soi",
    "email_cum_n_unique_user_ids_7d",
    "email_cum_n_raw_table_sources_7d",
    "email_cum_n_orders_7d",
    "email_rolling_avg_order_revenue_7d",
    "email_cum_revenue_usd_7d",
    "email_rolling_avg_soi_to_order_diff_hours_7d",
    "email_cum_n_unique_user_ids_28d",
    "email_cum_n_raw_table_sources_28d",
    "email_cum_n_orders_28d",
    "email_rolling_avg_order_revenue_28d",
    "email_cum_revenue_usd_28d",
    "email_rolling_avg_soi_to_order_diff_hours_28d",
    "email_cum_n_unique_user_ids_3m",
    "email_cum_n_raw_table_sources_3m",
    "email_cum_n_orders_3m",
    "email_rolling_avg_order_revenue_3m",
    "email_cum_revenue_usd_3m",
    "email_rolling_avg_soi_to_order_diff_hours_3m",
    "email_cum_n_unique_user_ids_ever",
    "email_cum_n_raw_table_sources_ever",
    "email_cum_n_orders_ever",
    "email_rolling_avg_order_revenue_ever",
    "email_cum_revenue_usd_ever",
    "email_rolling_avg_soi_to_order_diff_hours_ever",
    "email_avg_user_revenue_0h_24h_w28d",
    "email_avg_user_revenue_24h_48h_w28d",
    "email_avg_user_revenue_0h_48h_w28d",
    "email_avg_user_revenue_0h_24h_ever",
    "email_avg_user_revenue_24h_48h_ever",
    "email_avg_user_revenue_0h_48h_ever",
    "email_avg_user_revenue_30d_ever",
]

cum_perc_revenue_map = {
    "cum_perc_revenue_usd_hourly_1": "cum_perc_revenue_usd_hourly_01",
    "cum_perc_revenue_usd_hourly_2": "cum_perc_revenue_usd_hourly_02",
    "cum_perc_revenue_usd_hourly_3": "cum_perc_revenue_usd_hourly_03",
    "cum_perc_revenue_usd_hourly_4": "cum_perc_revenue_usd_hourly_04",
    "cum_perc_revenue_usd_hourly_5": "cum_perc_revenue_usd_hourly_05",
    "cum_perc_revenue_usd_hourly_6": "cum_perc_revenue_usd_hourly_06",
    "cum_perc_revenue_usd_hourly_7": "cum_perc_revenue_usd_hourly_07",
    "cum_perc_revenue_usd_hourly_8": "cum_perc_revenue_usd_hourly_08",
    "cum_perc_revenue_usd_hourly_9": "cum_perc_revenue_usd_hourly_09",
}

# categorical columns
high_cardinality_columns = [
    "aff_id",
    "site_alias",
    "user_site_alias",
]
one_hot_columns = [
    "country",
    "device",
    "user_gender",
    "user_marital_status",
    "user_registration_country",
    "user_registration_device",
    "user_seek_gender",
]

# max scalers
max_scalers = [
    "label_id",
    "payout",
    "user_age",
    "user_birth_day_of_month",
    "user_birth_month",
    "user_days_to_closest_birthday",
    "user_birth_day_of_month",
    "user_looking_for_age_max",
    "user_looking_for_age_min",
    "user_profile_description_length",
    "user_registration_day_of_month",
    "user_registration_isoweek",
    "user_registration_month",
    "user_registration_year",
    "user_registration_day_of_week",
    "user_registration_part_of_day",
    "soi_to_max_order_created_at_diff_days",
]

# log scalers
log_scalers = [
    "avg_user_order_revenue_usd_0h_24h",
    "avg_user_order_revenue_usd_0h_48h",
    "avg_user_order_revenue_usd_24h_48h",
    "diff_n_user_orders_24h_48h_vs_0h_24h",
    "n_user_orders_0h_24h",
    "n_user_orders_0h_48h",
    "n_user_orders_24h_48h",
    "perc_diff_avg_user_order_revenue_usd_24h_48h_vs_0h_24h",
    "perc_diff_n_user_orders_24h_48h_vs_0h_24h",
    "sum_revenue_0h_24h",
    "sum_revenue_0h_48h",
    "sum_revenue_24h_48h",
    "user_first_order_revenue_usd",
    "user_hours_to_first_order",
    "user_label_id",
    "user_registration_confirmation_minutes_diff",
    "user_revenue_usd_30d",
    "user_revenue_usd_60d",
    "user_revenue_usd_90d",
    "diff_avg_user_order_revenue_usd_24h_48h_vs_0h_24h",
]

targets = [
    "user_revenue_usd_30d",
    "user_revenue_usd_60d",
    "user_revenue_usd_90d",
]
